name: Number 93
favicon: null
layout_spectrum: 0.51157
typography_spectrum: 0.96842
title: My place on the internet
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030301'
    - '#fefefe'
    - '#423b30'
    - '#a6b7ad'
    - '#a58b66'
  brandStrength: 0.75
  lightness: 0.3125
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
